version: '3'

services:
  backend:
    container_name: lastgift-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules

  frontend:
    container_name: lastgift-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '4200:4200'
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules

  db:
    container_name: lastgift-db
    platform: linux/x86_64
    image: mysql:5.7
    restart: 'always'
    ports:
      - '3306:3306'
    volumes:
      - ./database/mysql/data/mysql:/var/lib/mysql
      - ./database/mysql/logs/mysql:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: lastgift
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
